# -*- coding: utf-8 -*-
"""streamlittest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-hqhyXUeLtMyK7n1VcbWVXXHsTuAthv
"""

import streamlit as st

# --- Funkcje do zarządzania magazynem ---

def initialize_inventory():
    """Inicjalizuje magazyn w zmiennej session_state Streamlit."""
    if 'inventory' not in st.session_state:
        # Przykładowe początkowe dane
        st.session_state.inventory = [
            {"id": 1, "name": "Młotek", "quantity": 15},
            {"id": 2, "name": "Śrubokręt krzyżakowy", "quantity": 30},
            {"id": 3, "name": "Puszka farby (biała)", "quantity": 5},
        ]

def get_next_item_id():
    """Zwraca kolejny dostępny ID dla nowego towaru."""
    if not st.session_state.inventory:
        return 1
    # Znajduje maksymalny ID i dodaje 1
    return max(item["id"] for item in st.session_state.inventory) + 1

def add_item(name, quantity):
    """Dodaje nowy towar do magazynu."""
    if name and quantity > 0:
        new_id = get_next_item_id()
        st.session_state.inventory.append({
            "id": new_id,
            "name": name,
            "quantity": quantity
        })
        st.success(f"Dodano towar: **{name}** (ID: {new_id})")
    else:
        st.error("Nazwa i ilość muszą być poprawne.")

def delete_item(item_id):
    """Usuwa towar o podanym ID z magazynu."""
    # Używamy list comprehension do stworzenia nowej listy bez usuwanego elementu
    st.session_state.inventory = [
        item for item in st.session_state.inventory if item["id"] != item_id
    ]
    st.warning(f"Usunięto towar o ID: **{item_id}**")

# --- Interfejs użytkownika Streamlit ---

def main():
    st.set_page_config(page_title="Prosty Magazyn", layout="wide")
    st.title("📦 Prosty System Zarządzania Magazynem")

    # Inicjalizacja magazynu przy pierwszym uruchomieniu
    initialize_inventory()

    # --- Kolumny dla lepszego układu ---
    col1, col2 = st.columns([1, 2])

    # --- Sekcja Dodawania (Kolumna 1) ---
    with col1:
        st.header("➕ Dodaj Nowy Towar")

        # Formularz do dodawania towaru
        with st.form("add_item_form", clear_on_submit=True):
            new_name = st.text_input("Nazwa Towaru")
            # Używamy number_input dla ilości, upewniając się, że jest to liczba całkowita >= 1
            new_quantity = st.number_input("Ilość", min_value=1, step=1, value=1)

            submitted = st.form_submit_button("Dodaj do Magazynu")

            if submitted:
                # Używamy funkcji do dodania, aby odświeżyć stan
                add_item(new_name, int(new_quantity))

    # --- Sekcja Usuwania (Kolumna 1) ---
    with col1:
        st.header("🗑️ Usuń Towar")

        # Pobieramy listę ID do wyboru
        item_ids = [item["id"] for item in st.session_state.inventory]

        if item_ids:
            # Dropdown do wyboru ID do usunięcia
            id_to_delete = st.selectbox(
                "Wybierz ID Towaru do usunięcia",
                options=item_ids,
                index=0
            )

            if st.button("Usuń Wybrany Towar"):
                delete_item(id_to_delete)
                # Ponowne uruchomienie aplikacji po usunięciu (dla lepszego odświeżenia selectboxa)
                st.experimental_rerun()
        else:
            st.info("Brak towarów do usunięcia.")


    # --- Sekcja Wyświetlania (Kolumna 2) ---
    with col2:
        st.header("📋 Aktualny Stan Magazynu")

        if st.session_state.inventory:
            # Wyświetlenie danych w formie tabeli (data frame)
            # Użycie st.dataframe dla ładniejszego i interaktywnego wyświetlania
            st.dataframe(st.session_state.inventory, use_container_width=True)

            st.markdown(f"**Całkowita liczba unikalnych towarów:** `{len(st.session_state.inventory)}`")
        else:
            st.info("Magazyn jest pusty! Dodaj pierwszy towar.")

if __name__ == "__main__":
    main()